refresh-project/Controllers/DeteksiController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AccessModel;
using ViewModel;

namespace refresh_project.Controllers
{
    public class DeteksiController : Controller
    {
        public static string messageTemp { get; set; }
        public ActionResult IndexRedirector(string message) {
            messageTemp = message;
            return RedirectToAction("Index");
        }
        // GET: Deteksi
        public ActionResult Index()
        {
            ViewBag.alertMessage = messageTemp;
            messageTemp = string.Empty;
            return View("Index");
        }

        public ActionResult Add() {
            return View();
        }

        [HttpPost]
        public ActionResult Add(biodataViewModel data) {
            data.created_by = 1;
            bool AddResult = biodataAccessModel.Insert(data);
            if (AddResult == true)
            {
                return RedirectToAction("IndexRedirector", new { message = "Data berhasil disimpan." });
            }
            else {
                ViewBag.Message = biodataAccessModel.Message;
                return View();
            }
        }

        public ActionResult List() {
            var list = biodataAccessModel.GetListAll();
            return PartialView(list);
        }

        public ActionResult Edit(long Id) {
            return View(biodataAccessModel.GetDetails(Id));
        }
        [HttpPost]
        public ActionResult Edit(biodataViewModel data) {
            bool editResult = biodataAccessModel.Update(data);
            if (editResult == true)
            {
                return RedirectToAction("IndexRedirector", new { message = "Data berhasil diubah." });
            }
            else {
                ViewBag.Message = biodataAccessModel.Message;
                return View();
            }
        }

        public ActionResult Details(long Id) {
            biodataViewModel result = new biodataViewModel();
            result = biodataAccessModel.GetDetails(Id);
            return PartialView(result);
        }
        public ActionResult Delete(long Id) {
            bool delResult = biodataAccessModel.Delete(Id);
            if (delResult == true)
            {
                return RedirectToAction("IndexRedirector", new { message = "Data berhasil dinonaktifkan." });
            }
            else { 
                return RedirectToAction("IndexRedirector", new { message = "Mohon maaf terjadi kesalahan, silakan coba lagi." });
            }
        }
    }
}

refresh-project/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace refresh_project.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

refresh-project/Views/Deteksi/Add.cshtml
@model ViewModel.biodataViewModel

@{
    ViewBag.Title = "Add";
}

<h2>Add</h2>
@if (ViewBag.Message != null && ViewBag.Message.ToLower().Contains("cannot insert duplicate key"))
{
    @:<div class="alert alert-danger" role="alert">NPM yang anda masukkan sudah terdaftar. Silahkan masukkan NPM lain.</div>
    }

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>biodataViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NPM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NPM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NPM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Umur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Umur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Umur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jenis_Kelamin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div>
                    <input type="radio" id="JK_Laki-laki" name="Jenis_Kelamin" value="True"
                           checked>
                    <label for="JK_Laki-laki">Laki-laki</label>
                </div>
                <div>
                    <input type="radio" id="JK_Perempuan" name="Jenis_Kelamin" value="False">
                    <label for="JK_Perempuan">Perempuan</label>
                </div>
                @Html.ValidationMessageFor(model => model.Jenis_Kelamin, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Asal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Asal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Asal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Domisili, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div>
                    <input type="radio" id="Domisili-Karawang" name="Domisili" value="Karawang"
                           checked>
                    <label for="Karawang">Karawang</label>
                </div>

                <div>
                    <input type="radio" id="Domisili-lain" name="Domisili" value="">
                    Domisili lain : 
                    <input class="form-control text-box single-line" data-val="true" id="Domisili" name="Domisili" type="text" value="">
                </div>
                @Html.ValidationMessageFor(model => model.Domisili, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

refresh-project/Views/Deteksi/Details.cshtml
@model ViewModel.biodataViewModel

<div>
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Email)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Email)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Nama)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Nama)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NPM)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NPM)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Umur)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Umur)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Jenis_Kelamin)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.genderName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Telp)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Telp)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Alamat)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Alamat)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Asal)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Asal)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Domisili)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Domisili)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.created_on)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.created_on)
        </dd>

    </dl>
</div>

refresh-project/Views/Deteksi/Edit.cshtml
@model ViewModel.biodataViewModel

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>
@if (ViewBag.Message != null && ViewBag.Message.ToLower().Contains("cannot insert duplicate key"))
{
    @:<div class="alert alert-danger" role="alert">NPM yang anda masukkan sudah terdaftar. Silahkan masukkan NPM lain.</div>
}

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>biodataViewModel</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Email, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Email, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Nama, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Nama, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Nama, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NPM, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NPM, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NPM, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Umur, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Umur, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Umur, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Jenis_Kelamin, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.Jenis_Kelamin)
                    @Html.ValidationMessageFor(model => model.Jenis_Kelamin, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Telp, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Telp, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Telp, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Alamat, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Alamat, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Alamat, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Asal, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Asal, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Asal, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Domisili, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Domisili, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Domisili, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

refresh-project/Views/Deteksi/Index.cshtml
@{
    ViewBag.Title = "Peserta Deteksi Dini Covid-19";
}

<h2>Peserta Deteksi Dini Covid-19</h2>
@if (ViewBag.alertMessage != string.Empty && ViewBag.alertMessage != null)
{
    <div class="alert alert-success" role="alert">
        @ViewBag.alertMessage
    </div>
}

<a href='@Url.Action("Add", "Deteksi")' class="btn btn-primary">Daftar</a> <a id="listPeserta" class="btn btn-default">Lihat peserta</a>

<div id="listData"></div>

<!-- Modal -->
<div class="modal fade" id="modal1" tabindex="-1" role="dialog">
    <div class="modal-dialog modal-dialog-scrollable" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalScrollableTitle">Details</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body" id="modal1-body">
                ...
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
            </div>
        </div>
    </div>
</div>

@section Scripts {
    <script>
        var loadingBar = '<div class="progress-bar progress-bar-striped progress-bar-animated" role="progressbar" aria-valuemin="0" style="width: 100%"></div>';

        $("#listPeserta").on("click", function () {
            $("#listData").html(loadingBar);
            $.ajax({
                url: '@Url.Action("List", "Deteksi")',
                type: 'get',
                success: function (result) {
                    $("#listData").html(result);
                }
            })
        });

        $(document).on("click", ".btnDetails", function () {
            let dataId = $(this).attr("data-id");
            $("#modal1").modal("show");
            $.ajax({
                url: '@Url.Action("Details", "Deteksi")' + '/' + dataId,
                type: 'get',
                success: function (result) {
                    $("#modal1-body").html(result);
                }
            });
        })
    </script>
}

refresh-project/Views/Deteksi/List.cshtml
@model IEnumerable<ViewModel.biodataViewModel>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Email)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nama)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NPM)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Alamat)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Email)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Nama)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NPM)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Alamat)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.id }) |
            <a href="#" data-id="@item.id" class="btnDetails">Details</a>
            @*@Html.ActionLink("Details", "Details", new { id=item.id })*@ |
            @Html.ActionLink("Delete", "Delete", new { id=item.id })
        </td>
    </tr>
}

</table>

refresh-project/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

refresh-project/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

refresh-project/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<a class="btn btn-primary" href='@Url.Action("Index", "Deteksi")'>Pendeteksian covid-19</a>